import { createFileRoute } from "@tanstack/react-router";
import { PageHeader, MockBadge } from "@/components/layout/AppLayout";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { useAuth, getEffectivePermissions, PAPEL_LABEL, PERMISSAO_LABEL, PERMISSOES, type Papel, type Permissao } from "@/lib/auth-store";
import { addAudit } from "@/lib/audit-store";
export const Route = createFileRoute("/usuarios")({ head: () => ({ meta: [{ title: "Usuários e Permissões · CRM Clube04" }] }), component: Usuarios });
const papeis:Papel[]=["atendente","lider","administrador"];
function Usuarios(){const{users,currentUser,updateUser}=useAuth();const setPapel=(id:string,papel:Papel)=>updateUser(id,u=>{addAudit({action:"usuario_alterado",actorName:currentUser?.nome??"Usuário local",actorRole:currentUser?.papel??"sistema",summary:`Papel de ${u.nome} alterado para ${PAPEL_LABEL[papel]}`});return{...u,papel}});const togglePermissao=(id:string,p:Permissao)=>updateUser(id,u=>{const tem=getEffectivePermissions(u).includes(p);const extra=u.permissoesExtra.filter(x=>x!==p);const neg=u.permissoesNegadas.filter(x=>x!==p);const updated=tem?{...u,permissoesExtra:extra,permissoesNegadas:[...neg,p]}:{...u,permissoesExtra:[...extra,p],permissoesNegadas:neg};return updated;});return <><PageHeader title="Usuários e Permissões" subtitle="Perfis locais para testar níveis de acesso." badge={<MockBadge/>}/><div className="px-8 py-6 space-y-4">{users.map(u=>{const efetivas=getEffectivePermissions(u);return <div key={u.id} className="rounded-xl border border-border bg-card p-5 space-y-4"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="font-display font-semibold text-lg">{u.nome}</div><div className="text-sm text-muted-foreground">{u.email}</div></div><div className="flex items-center gap-3 flex-wrap"><Select value={u.papel} onValueChange={(v)=>setPapel(u.id,v as Papel)}><SelectTrigger className="w-44 h-9"><SelectValue/></SelectTrigger><SelectContent>{papeis.map(p=><SelectItem key={p} value={p}>{PAPEL_LABEL[p]}</SelectItem>)}</SelectContent></Select><div className="flex items-center gap-2"><Label className="text-xs">Ativo</Label><Switch checked={u.ativo} onCheckedChange={()=>updateUser(u.id,x=>({...x,ativo:!x.ativo}))}/></div><div className="flex items-center gap-2"><Label className="text-xs">Aparece como atendente</Label><Switch checked={u.apareceComoAtendente} onCheckedChange={()=>updateUser(u.id,x=>({...x,apareceComoAtendente:!x.apareceComoAtendente}))}/></div></div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-2">{PERMISSOES.map(p=><label key={p} className="flex items-center justify-between gap-3 rounded-lg border border-border bg-muted/20 px-3 py-2 text-sm"><span>{PERMISSAO_LABEL[p]}</span><Switch checked={efetivas.includes(p)} onCheckedChange={()=>togglePermissao(u.id,p)}/></label>)}</div></div>})}</div></>}
